name: Build

on: [push, pull_request, workflow_dispatch, repository_dispatch]

jobs:
  build_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Building Docker Images & Publishing
        run: |
          sudo chmod u+x ./do.sh
          sudo DOCKER_HUB_USERNAME='${{ secrets.DOCKER_HUB_USERNAME }}' DOCKER_HUB_ACCESS_TOKEN='${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}' ./do.sh cicd