# Build workflow does the following:
#   - checkout all files
#   - get the latest version number
#   - setup python 3.x env
#   - install python dependencies
#   - Set up Docker Build
#   - Build and push to DockerHub


name: Build

on: [push, pull_request, workflow_dispatch, repository_dispatch]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Installing Docker on GitHub Runner
        uses: docker-practice/actions-setup-docker@master
        run: |
          docker ps -a
      